
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'pricing_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'pricing_analytics' # ← this should match the profile name in profiles.yml

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets:  ["target","dbt_packages"] 
     # directories to be removed by `dbt clean`



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  pricing_analytics: # Phải khớp với name ở dòng 5
    stg:
      +materialized: view
      +schema: raw
    refined:
      +materialized: ephemeral # Hoặc view tùy bạn
      +schema: intermediate
    marts:
      +materialized: table
      +schema: main

